name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Give execute permission to Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build project with Gradle
      run: ./gradlew build
        
    - name: Build Docker Image
      run: |
        docker build --tag cristopher5353/cart-service:1.0.0 --build-arg JAR_FILE=build/libs/cart-service-0.0.1-SNAPSHOT.jar .

    - name: Push Docker Image
      run: |
        docker push cristopher5353/cart-service:1.0.0
